### PR TITLE
Update build and codes to make it work with updated scala and library version

### PR DESCRIPTION
**Pull request by viirya**

### CODE REVIEW

**Comment by ms705** [comment]
Thanks for this patch! Unfortunately, I no longer have commit access to this repo, since it's under the Google organization now. However, @johnwilkes should have access and should be able to merge this (useful and sensible-looking) PR, or will know who can do it.

Thanks!
M.

**Comment by johnwilkes** [comment]
blast from the past!  @viirya - please could you check that this still makes sense?  I recently got admin access to the repo, but I'm very much a GitHub noob.  Many thanks!

**Comment by viirya** [comment]
wow, surprised that I can still get feedback after so long time. :) thanks.

Yea, I just tried to build it. Looks still okay.

**Comment by johnwilkes** [comment]
Great - thanks!

**Pull request merged**
